---
- name: install visual c++ redistributable 2013
  win_chocolatey:
    name: vcredist2013
    state: present

- name: Install mysql database
  win_chocolatey:
    name: mysql
    state: present

- name: Start MySQL
  win_command: "C:\tools\mysql\current\bin\mysqld --install"