---
- name: install visual c++ redistributable 2013
  win_chocolatey:
    name: vcredist2013
    state: present

- name: Install mysql database
  win_chocolatey:
    name: mysql
    state: present

- name: Firewall rule to allow MySQL on TCP port 3306
  win_firewall_rule:
    name: MySQL_3306
    localport: 3306
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: yes

- name: Setup mysql root password 
  win_command: C:\tools\mysql\current\bin\mysqladmin -u root -p oldpassword mysql!234

- name: Install MySQL as a windows service
  win_command: C:\tools\mysql\current\bin\mysqld --install